### ISSUE TITLE
Can't make it run.

### ISSUE THREAD

**Issue by shaikhabbas** [meerkat-cv/ava_preview#10]
![image](https://cloud.githubusercontent.com/assets/25801596/22989397/8b88b5be-f3d7-11e6-816a-558006b93bfd.png)

**Comment by vmktharun** [comment]
The "ava-release" folder which suppose to have the library files , has only one file 'ava-release.iml' in the zip i have downloaded. I too get the same error when i try to run.

**Comment by reaurr** [comment]
compile project(':ava-release') not found

**Comment by Siignature** [comment]
Same trouble

**Comment by gustavofuhr** [comment]
Sorry for not making it clear, but the ava library is commercially available and
not open sourced. We can provide trials if you contact us directly.

Anyway, I will change the readme to clarify that. Thanks.
