### ISSUE TITLE
Missing AVA

### ISSUE THREAD

**Issue by vndn-developers** [meerkat-cv/ava_preview#2]
Error when import br.com.meerkat.ava.Ava;
Hello, I am very interested in this project.
Looks like it is missing AVA module.
Hope you will share it

**Comment by gustavofuhr** [comment]
Hello @vndn-developers,

The AVA module is our spoofing and face detection SDK, but it is not open source.
If you are interested in testing this SDK, please contact us at meerkat.cv@gmail.com and
we can arrange to send you a demo.
